name: ExampleWorkflow${self:service}${opt:stage, 'dev'}
definition:
  Comment: "Example Workflow"
  StartAt: exampleStep
  States:
    exampleStep:
      Type: Task
      Resource:
        Fn::GetAtt: [example-step-lambda, Arn]
      TimeoutSeconds: 28
      Next: done
    done:
      Type: Succeed
