service: ${env:APP_NAME, 'tsh-example-app'}
useDotenv: true
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-log-retention
  - serverless-step-functions

package:
  individually: true

custom:
  logRetentionInDays: 30
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  environment:
    APP_NAME: ${env:APP_NAME, 'tsh-example-app'}
    AWS_LAMBDAS_REGION: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - states:StartExecution
      Resource:
        - "*"

functions:
  - ${file(functions/migrations/function.yml)}
  - ${file(functions/example-lambda/function.yml)}
  - ${file(workflows/example-workflow/example-step/function.yml)}
  # PLOP_ADD_LAMBDA

stepFunctions:
  stateMachines:
    ExampleWorkflow: ${file(workflows/example-workflow/workflow.yml)}
  # PLOP_ADD_WORKFLOW_STATE_MACHINE

resources:
  Outputs:
    ExampleWorkflowStateMachine:
      Description: Example workflow state machine Arn
      Value:
        Ref: ExampleWorkflow${self:service}${opt:stage, 'dev'}
    # PLOP_ADD_WORKFLOW_RESOURCE
