service: ${env:APP_NAME, 'tsh-example-app'}
useDotenv: true
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-log-retention

package:
  individually: true

custom:
  logRetentionInDays: 30
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  environment:
    APP_NAME: ${env:APP_NAME, 'tsh-example-app'}
    AWS_LAMBDAS_REGION: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}

functions:
  - ${file(lambdas/migrations/function.yml)}
  - ${file(lambdas/example-lambda/function.yml)}
  # PLOP_ADD_LAMBDA
