name: {{properCase name}}${self:service}${opt:stage, 'dev'}
definition:
  Comment: "{{properCase name}} Workflow"
  StartAt: exampleStep
  States:
    # PLOP_ADD_WORKFLOW_STEP
  fail:
    Type: Fail
  done:
    Type: Succeed
